#!/bin/bash
# Substitui e flexibiliza o uso do docker-compose,
# existem os parametros padrão mas você pode passar os adicionais que quiser
# no futuro será criado um snippet para esse script

BASE_NAME="pedido-mysql"
IMAGE_NAME="$BASE_NAME:1.0"

if [ "$1" == "build" ]; then

	docker build --rm --tag $IMAGE_NAME `dirname $0` "${@:2}"

# modo para testes 
elif [ "$1" == "up" ]; then

	docker rm -f $BASE_NAME &> /dev/null
	docker run --expose 3306 \
		--hostname $BASE_NAME \
		--name $BASE_NAME \
		--detach \
		--env \
				"MYSQL_ROOT_PASSWORD=root" \
		$IMAGE_NAME "${@:2}"

# modo para desenvolver (a base fica computador)
elif [ "$1" == "up-dev" ]; then

	docker rm -f $BASE_NAME &> /dev/null
	docker run --expose 3306 \
		--hostname $BASE_NAME \
		--name $BASE_NAME \
		--detach \
		--env \
				"MYSQL_ROOT_PASSWORD=root" \
		--volume \
				/var/lib/mageddo/$BASE_NAME:/var/lib/mysql \
		$IMAGE_NAME "${@:2}"

elif [ "$1" == "clear" ]; then

	echo "deleting the containers..."
	docker rm -f $BASE_NAME &> /dev/null

	echo "deleting images ..."
	docker rmi -f $IMAGE_NAME &> /dev/null
	echo "done!"

else
	echo "informe a tarefa"
	exit -1
fi